name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Use the v2 version for improved experience
      with:
        submodules: recursive  # This is for handling submodules

    - name: Build
      run: cargo build --verbose
      working-directory: src/

    - name: Run tests
      run: cargo test --verbose
      working-directory: src/
